### ISSUE TITLE
Install .NET 5.0

### ISSUE THREAD

**Issue by sharknice** [aiarena/aiarena-client#24]
Install .NET 5.0 on the ladder so dotnetcore bots can built in the newest version of dotnetcore.
https://dotnet.microsoft.com/download/dotnet/5.0

The only version of dotnetcore currently installed on the ladder is 2.2 which has reached end of life, meaning it is no longer supported by Microsoft.  This is a major pain for anyone developing a new bot in dotnetcore.

Multiple versions of .net core can co-exist so installing the new version will not affect bots using 2.2.

**Comment by sharknice** [comment]
This is the error log trying to run a .NET 5.0 bot
[SharkyExample-error.log](https://github.com/aiarena/aiarena-client/files/5645464/SharkyExample-error.log)

I have uploaded a .NET 5.0 bot to be able to test the install with : https://aiarena.net/bots/215/

**Comment by lladdy** [comment]
Looks good now:
https://aiarena.net/matches/437177/
