### ISSUE TITLE
Redo the config injection logic in the AC

### ISSUE THREAD

**Issue by eladyaniv01** [aiarena/aiarena-client#35]
right now we inject our secret variables via a binded file ( `config.py` ) 
when we move to rancher + kubernetes we wont be able to do that in a robust way that allows scaling up and down 

We need  to have a mechanic for injecting a new /  or a running AC with an API key,  and an Endpoint
(we  would also want to be able to change endpoints / keys  on running containers )

**Comment by lladdy** [comment]
Already done
